version: '3'

services:
  tests:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379
      - MEMCACHED_URL=memcached://memcached:11211
    depends_on:
      - redis
      - memcached
  redis:
    image: redis:latest
  memcached:
    image: memcached:latest
